- hosts: master 
  user: sdp
  become: yes
  connection: ssh
  tasks:
     - name: Update
       command: apt update -y 

     - name: Install munge
       action: apt name=munge state=present

     - name: Install vim
       action: apt name=vim state=present

     - name: Install build-essential
       action: apt name=build-essential state=present

     - name: Install git
       action: apt name=git state=present

     - name: Install mariadb-server
       action: apt name=mariadb-server state=present

     - name: Install wget
       action: apt name=wget state=present

     - name: Install slurmd 
       action: apt name=slurmd state=present
     
     - name: Install slurm-client
       action: apt name=slurm-client state=present

     - name: Install slurmctld
       action: apt name=slurmctld state=present

     - name: Install python
       command: apt install sudo python3.9 python3-pip -y

     - name: Copy slurm.conf to remote server
       copy:
          src: /home/sdp/Slurm-Ansible/SLURM-BAREMETAL-AWS/slurm.conf
          dest: /etc/slurm-llnl/

     - name: Copy cgroup.conf to remote server
       copy:
          src: /home/sdp/Slurm-Ansible/SLURM-BAREMETAL-AWS/cgroup.conf
          dest: /etc/slurm-llnl/

     - name: Copy docker-entrypoint.sh to remote server
       copy:
          src: /home/sdp/Slurm-Ansible/SLURM-BAREMETAL-AWS/docker-entrypoint.sh
          dest: /etc/slurm-llnl/

     - name: Copy Munge key
       copy:
          src: /home/sdp/Slurm-Ansible/SLURM-BAREMETAL-AWS/munge.key
          dest: /etc/munge/

     - name: Start munge service
       action: service name=munge state=restarted

     - name: Start slurmctld service
       action: service name=slurmctld state=restarted
